---
name: "Workflow call: Render Readme"

on:
  workflow_call:
    secrets:
      RAFARIBE_APP_ID:
        description: "The ID of the GitHub App"
        required: true
      RAFARIBE_APP_PRIVATE_KEY:
        description: "The private key of the GitHub App"
        required: true

jobs:
  render-readme:
    name: Render README
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: "${{ secrets.RAFARIBE_APP_ID }}"
          private_key: "${{ secrets.RAFARIBE_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: Install Python Requirements
        run: |
          pip install -r ./.ci/scripts/requirements.txt && pip freeze

      - name: Render README
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          python ./.ci/scripts/render-readme.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit
        with:
          file_pattern: "README.md"
          commit_message: Render README.md
          commit_user_name: "rafaribe-bot[bot]"
          commit_user_email: 87358111+rafaribe-bot[bot]@users.noreply.github.com
          commit_author: rafaribe-bot[bot] <87358111+rafaribe-bot[bot]@users.noreply.github.com>
